// Import all settings
import {
  GLOBAL_SETTINGS_KEYS,
  GLOBAL_SETTINGS,
  GLOBAL_SETTINGS_TYPES,
} from "./settings/GLOBAL_SETTINGS_KEYS";

import {
  MAIL_SERVICE_SETTINGS_KEYS,
  MAIL_SERVICE_SETTINGS,
  Mail_SETTINGS_TYPES,
} from "./settings/MAIL_SERVICE_KEYS";

import {
  FIREBASE_SETTINGS_KEYS,
  FIREBASE_SETTINGS,
  FIREBASE_SETTINGS_TYPES,
} from "./settings/STORAGE_SETTINGS_KEYS";

import {
  PAYMENT_SETTINGS_KEYS,
  PAYMENT_SETTINGS,
  PAYMENT_SETTINGS_TYPES,
} from "./settings/PAYMENT_SETTINGS_KEYS";

import {
  SOCIAL_MEDIA_SETTINGS_KEYS,
  SOCIAL_MEDIA_SETTINGS,
  SOCIAL_MEDIA_SETTINGS_TYPES,
} from "./settings/SOCIAL_MEDIA_KEYS";

import {
  MESSAGING_SERVICE_SETTINGS_KEYS,
  MESSAGING_SERVICE_SETTINGS,
  MESSAGING_SERVICE_TYPES,
} from "./settings/MESSAGING_SERVICE_KEYS";
import {
  DESIGN_SCHEMA_SETTINGS_KEYS,
  DESIGN_SCHEMA_SETTINGS,
  DESIGN_SCHEMA_SETTINGS_TYPES,
} from "./settings/DESIGN_SCHEMA_KEYS";
// Combine all keys
export const SETTINGS_KEYS = {
  ...GLOBAL_SETTINGS_KEYS,
  ...MAIL_SERVICE_SETTINGS_KEYS,
  ...FIREBASE_SETTINGS_KEYS,
  ...PAYMENT_SETTINGS_KEYS,
  ...SOCIAL_MEDIA_SETTINGS_KEYS,
  ...MESSAGING_SERVICE_SETTINGS_KEYS,
  ...DESIGN_SCHEMA_SETTINGS_KEYS,
} as const;

// Combine all settings
export const SETTINGS_GUIDE = {
  ...GLOBAL_SETTINGS,
  ...MAIL_SERVICE_SETTINGS,
  ...FIREBASE_SETTINGS,
  ...PAYMENT_SETTINGS,
  ...SOCIAL_MEDIA_SETTINGS,
  ...MESSAGING_SERVICE_SETTINGS,
  ...DESIGN_SCHEMA_SETTINGS,
} as const;

export type SettingsInterface = GLOBAL_SETTINGS_TYPES &
  Mail_SETTINGS_TYPES &
  FIREBASE_SETTINGS_TYPES &
  PAYMENT_SETTINGS_TYPES &
  SOCIAL_MEDIA_SETTINGS_TYPES &
  MESSAGING_SERVICE_TYPES &
  DESIGN_SCHEMA_SETTINGS_TYPES;

export type PublicKeys = {
  [K in keyof typeof SETTINGS_GUIDE]: (typeof SETTINGS_GUIDE)[K]["visibility"] extends "public"
    ? K
    : never;
}[keyof typeof SETTINGS_GUIDE];

export type PrivateKeys = {
  [K in keyof typeof SETTINGS_GUIDE]: (typeof SETTINGS_GUIDE)[K]["visibility"] extends "private"
    ? K
    : never;
}[keyof typeof SETTINGS_GUIDE];

export type ValidSettingKey =
  | keyof GLOBAL_SETTINGS_TYPES
  | keyof Mail_SETTINGS_TYPES
  | keyof FIREBASE_SETTINGS_TYPES
  | keyof PAYMENT_SETTINGS_TYPES
  | keyof SOCIAL_MEDIA_SETTINGS_TYPES
  | keyof MESSAGING_SERVICE_TYPES;
