import {
  HomeOutlined,
  PlusOutlined,
  UploadOutlined,
  DashboardOutlined,
  BookOutlined,
  FormOutlined,
  PictureOutlined,
  SettingOutlined,
  TeamOutlined,
  UserOutlined,
  FileOutlined,
  LogoutOutlined,
  LoginOutlined,
  WalletOutlined,
} from "@ant-design/icons";

export const iconMapper: { [key: string]: React.ReactNode } = {
  HomeOutlined: <HomeOutlined />,
  UserOutlined: <UserOutlined />,
  TeamOutlined: <TeamOutlined />,
  BookOutlined: <BookOutlined />,
  PictureOutlined: <PictureOutlined />,
  PlusOutlined: <PlusOutlined />,
  UploadOutlined: <UploadOutlined />,
  SettingOutlined: <SettingOutlined />,
  FormOutlined: <FormOutlined />,
  FileOutlined: <FileOutlined />,
  WalletOutlined: <WalletOutlined />,
  DashboardOutlined: <DashboardOutlined />,
  LogoutOutlined: <LogoutOutlined />,
  LoginOutlined: <LoginOutlined />,
};
